services:
  # Backend Spring Boot Service
  - type: web
    name: spotify-media-player-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://spotify-media-player-frontend.onrender.com

  # Frontend Node.js Service
  - type: web
    name: spotify-media-player-frontend
    env: node
    buildCommand: cd frontend && npm install
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: BACKEND_URL
        value: https://spotify-media-player-backend.onrender.com
