services:
  - type: web
    name: spotify-media-player
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://spotify-media-player.onrender.com
